version: '3.8'

services:
  facturador-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: facturador-frontend
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - BACKEND_HOST=facturacion-backend # Nombre del contenedor backend
      - MINIO_HOST=minio # Nombre del contenedor MinIO

    ports:
      - "3001:80"
    networks:
      - dokploy-network
    restart: always

networks:
  dokploy-network:
    external: true
