version: '3.8'

services:
  facturador-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: facturador-frontend
    ports:
      - "3001:80"
    networks:
      - dokply
    restart: always

networks:
  dokply:
    name: dokply
    driver: bridge
